### ISSUE TITLE
Examples not working with go 1.16

### ISSUE THREAD

**Issue by dimiandre** [wealdtech/go-ens#7]
I think examples are not working anymore

this error happens when doing `ens.Resolve(client, domain)`

```
$:ens-updater dimiandre$ go run main.go 
# github.com/wealdtech/go-ens/v3/util
../../go/pkg/mod/github.com/wealdtech/go-ens/v3@v3.4.4/util/signer.go:31:11: cannot use func literal (type func(types.Signer, common.Address, *types.Transaction) (*types.Transaction, error)) as type bind.SignerFn in assignment
../../go/pkg/mod/github.com/wealdtech/go-ens/v3@v3.4.4/util/signer.go:44:11: cannot use func literal (type func(types.Signer, common.Address, *types.Transaction) (*types.Transaction, error)) as type bind.SignerFn in assignment

$:ens-updater dimiandre$ go version
go version go1.16 darwin/amd64
```

**Comment by mcdee** [comment]
You are most likely using a different version of go-ethereum from that against which go-ens was built.  Unfortunately go-ethereum does not follow semantic versioning as per go modules, so it commonly causes compilation errors.  Does it work if you change your version of `github.com/ethereum/go-ethereum` to 1.9.23 as per the go.mod of the latest release of go-ens?

**Comment by dimiandre** [comment]
Uh yes, using go-ether 1.9.23 works

thanks a lot!
